spring:
  application:
    name: eureka-api-getway
  zipkin:
    base-url: http://localhost:1106
  sleuth:
    sampler:
     percentage: 1.0  #全部都需要
server:
  port: 1101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

zuul:
  routes:
    api-consumer:
      path: /api-client/**      #映射服务的前置路径
      serviceId: eureka-client  #服务名
    api-consumerfeign:
      path: /api-feign/**
      serviceId: eureka-consumer-feign
    api-client:
      path: /client/**
      serviceId: eureka-client

